version: "3.4"

services:
  php:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www/html

  composer:
    image: composer:latest
    entrypoint: composer
    command: install
    volumes:
      - ./:/app
